server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: jms-template, jms-listener
# The values given here are actually the default values. But they are explicitly
# set here as an example of setting the Artemis properties.
  jms:
    template:
      receive-timeout: 5000
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false
      
---
spring:
  config:
    activate:
      on-profile: kafka-listener 
    
  kafka:
    bootstrap-servers: 43.200.164.243:9092
#    bootstrap-servers: 15.165.75.166:9092
    template:
      default-topic: tacocloud_orders
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos
